name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "develop"
      - uses: release-drafter/release-drafter@v5.9.0
        with:
         config-name: release-drafter.yml
           # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
           # config-name: my-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  name-template: 'v$NEXT_MINOR_VERSION 🌈'
  tag-template: 'v$NEXT_MINOR_VERSION'
  change-template:  '- $TITLE @$AUTHOR (#$NUMBER)'
  template: |
    ## Changes

    $CHANGES  
          
